# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 12:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=40, verbose_name='service')),
                ('session', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='session')),
            ],
            options={
                'verbose_name': 'authorization',
                'verbose_name_plural': 'authorizations',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, verbose_name='alias')),
                ('session', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='session')),
            ],
            options={
                'verbose_name': 'identity',
                'verbose_name_plural': 'identities',
            },
        ),
        migrations.AddField(
            model_name='authorization',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='gul.Identity', verbose_name='identity'),
        ),
    ]
