# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gul', '0003_auto_20160918_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='token'),
        ),
    ]
