# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import utils.sql
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gul', '0004_auto_20160918_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='room ID')),
                ('course_id', models.IntegerField(unique=True, verbose_name='course ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='course name')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
            bases=(models.Model, utils.sql.StandardIINEModelMixin),
        ),
    ]
